add requirements
KDanil2000/online-book-store pull request #1
Opened 2023-10-18 17:45 UTC by KDanil2000

2023-10-18 17:54 UTC, KDanil2000 commented
1

2023-10-19 14:52 UTC, liliia-ponomarenko requested changes
Good job! Let’s  fix a few mistakes ;)

2023-10-19 14:52 UTC, liliia-ponomarenko commented on pom.xml
> +</project>
Let’s  add one empty line

2023-10-19 14:52 UTC, liliia-ponomarenko commented on pom.xml
> +        </dependency>
Do you really need all these dependencies?

2023-10-19 14:52 UTC, liliia-ponomarenko commented on src/main/java/bookstore/OnlineBookStoreApplication.java
> +@EntityScan(basePackages = "model")
you can remove it

2023-10-19 14:52 UTC, liliia-ponomarenko commented on src/main/java/exceptions/EntityException.java
> +public class EntityException extends RuntimeException {
```suggestion
public class EntityNotFoundException extends RuntimeException {
```

2023-10-19 14:52 UTC, liliia-ponomarenko commented on src/main/java/model/Book.java
> +@Data
Lombok is a great library but be [attentive when using it with Entity](https://jpa-buddy.com/blog/lombok-and-jpa-what-may-go-wrong/) JFYI

2023-10-19 14:52 UTC, liliia-ponomarenko commented on src/main/java/service/impl/BookServiceImpl.java
> +
```suggestion
```

2023-10-19 14:52 UTC, liliia-ponomarenko commented on src/main/java/service/impl/BookServiceImpl.java
> +    @Autowired
This annotation is redundant (more details in spring documentation)

2023-10-23 06:08 UTC, Elena-Bruyako approved these changes
Good job! Let's remove redundant annotations)

2023-10-23 06:08 UTC, Elena-Bruyako commented on src/main/java/bookstore/OnlineBookStoreApplication.java
> +@EntityScan(basePackages = "model")
Redundant annotations

2023-10-23 10:26 UTC, merged