Add dto, controller, mapper
KDanil2000/online-book-store pull request #2
Opened 2023-10-23 12:29 UTC by KDanil2000

2023-10-24 08:38 UTC, liliia-ponomarenko requested changes
Great! A few minor mistakes  ;)

2023-10-24 08:38 UTC, liliia-ponomarenko commented on src/main/java/controller/BookController.java
> +@RequestMapping(value = "/api/books")
```suggestion
@RequestMapping("/books")
```

2023-10-24 08:38 UTC, liliia-ponomarenko commented on src/main/java/dto/BookDto.java
> +public class BookDto {
Let’s  use record for dtos

2023-10-24 08:38 UTC, liliia-ponomarenko commented on src/main/java/service/impl/BookServiceImpl.java
> +        return bookMapper.toDto(bookRepository.save(book));
can be inline variable

2023-10-25 06:10 UTC, Elena-Bruyako approved these changes
Good job!

2023-10-25 06:51 UTC, merged