GlobalExceptionHandler implementation
KDanil2000/online-book-store pull request #4
Opened 2023-10-29 21:08 UTC by KDanil2000

2023-10-30 11:44 UTC, Parashchuk approved these changes

2023-11-02 11:55 UTC, liliia-ponomarenko requested changes
Good job! Let’s  fix a few mistakes ;)

2023-11-02 11:55 UTC, liliia-ponomarenko commented on src/main/java/controller/BookController.java
>      public BookDto getBookById(@PathVariable Long id) {
```suggestion
    public BookDto getBookById(@Positive @PathVariable Long id) {
```
You can use Positive  validator here to

2023-11-02 11:55 UTC, liliia-ponomarenko commented on src/main/java/exceptions/CustomGlobalExceptionHandler.java
> +        return new ResponseEntity<>(body, HttpStatus.NOT_FOUND);
```suggestion
        body.put("errors", errors);
        return new ResponseEntity<>(body, HttpStatus.NOT_FOUND);
```
no need to pass status twice

2023-11-02 11:55 UTC, liliia-ponomarenko commented on src/main/java/model/Book.java
> +    private boolean isDeleted;
```suggestion
    @Column(nullable = false)
    private boolean isDeleted = false;
```

2023-11-02 11:55 UTC, liliia-ponomarenko commented on src/main/resources/application.properties
> +    spring.jpa.show-sql=true
Let’s  remove whitespaces

2023-11-02 11:55 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/01-create-table-books.yaml
> +                    nullable: false
Let’s  add one empty line at the end of the file (check  other files

2023-11-02 11:55 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/01-create-table-books.yaml
> +                  type: varchar(255)
Be careful, if you don't validate the input fields max size, it can cause SQL exception

2023-11-07 08:15 UTC, NazarSmith228 approved these changes
LGTM, but please pay attention to my comments

2023-11-07 08:15 UTC, NazarSmith228 commented on src/main/java/controller/BookController.java
> +    @ResponseStatus(HttpStatus.OK)
FYI

OK - is the default status, so you may skip it :)

2023-11-07 08:15 UTC, NazarSmith228 commented on src/main/java/dto/CreateBookRequestDto.java
>          String coverImage
pls add validation for max sizes here 

otherwise user input might cause error on DB layer

2023-11-08 20:39 UTC, merged