registration, authorization with jwt implementation
KDanil2000/online-book-store pull request #6
Opened 2023-11-09 19:42 UTC by KDanil2000

2023-11-14 15:22 UTC, vsych321 requested changes

2023-11-14 15:22 UTC, vsych321 commented on src/main/java/controller/AuthenticationController.java
> +@RequestMapping(value = "/api/auth")
instead of /api here, use it in application.properties in appropriate way

2023-11-14 15:22 UTC, vsych321 commented on src/main/java/controller/AuthenticationController.java
> +@Validated
you don't use it, so remove)

2023-11-14 15:22 UTC, vsych321 commented on src/main/java/controller/BookController.java
> +    @PreAuthorize("hasAnyRole('ROLE_ADMIN', 'ROLE_USER')")
it's better to use "hasRole" and write without prefix 'ROLE_', is  used by default  
```suggestion
    @PreAuthorize("hasRole('USER')")
```
the same with other lines of code!

2023-11-14 15:22 UTC, vsych321 commented on src/main/java/dto/user/UserLoginRequestDto.java
> +        String password) {
use @NotBlank instead of not null and add constraints with size

2023-11-14 15:22 UTC, vsych321 commented on src/main/java/dto/user/UserRegistrationRequestDto.java
> +        @NotNull @Email
don't use @NotNull with strings
```suggestion
        @NotBlank @Email
```
the same with other fields

2023-11-14 15:22 UTC, vsych321 commented on src/main/java/exceptions/RegistrationException.java
> +    }
do u really need this exception?

2023-11-14 15:22 UTC, vsych321 commented on src/main/java/jwt/JwtAuthenticationFilter.java
> +            return bearerToken.substring(7);
better make constant and you can use length instead magic number 7

2023-11-14 15:22 UTC, vsych321 commented on src/main/java/model/RoleName.java
> +}
u can write it inside Role class in case to minimize the size of your project

2023-11-14 15:22 UTC, vsych321 commented on src/main/resources/db/changelog/changes/03-create-table-roles.yaml
> +                    unique: true
missed empty line(check with other files)

2023-11-30 10:43 UTC, liliia-ponomarenko requested changes
Good job! Let’s  improve your solution ;)

2023-11-30 10:43 UTC, liliia-ponomarenko commented on pom.xml
> +        <dependency>
You already have liquibase plugin

2023-11-30 10:43 UTC, liliia-ponomarenko commented on pom.xml
> +        </dependency>
Do you use this dependency?

2023-11-30 10:43 UTC, liliia-ponomarenko commented on src/main/java/controller/AuthenticationController.java
> +@Validated
```suggestion
```
agree, Let’s  remove this annotation here

2023-11-30 10:43 UTC, liliia-ponomarenko commented on src/main/java/controller/AuthenticationController.java
> +
```suggestion
```

2023-11-30 10:43 UTC, liliia-ponomarenko commented on src/main/java/dto/user/UserLoginRequestDto.java
> +
```suggestion
```

2023-11-30 10:43 UTC, liliia-ponomarenko commented on src/main/java/dto/user/UserRegistrationRequestDto.java
> +        @NotNull @Size(min = 4, max = 32)
```suggestion
        @NotBlank @Size(min = 4, max = 32)
```

2023-11-30 10:43 UTC, liliia-ponomarenko commented on src/main/java/mapper/UserMapper.java
> +    void updateUser(UserLoginRequestDto updatedRequestDto, @MappingTarget User bookToUpdate);
```suggestion
    void updateUser(UserLoginRequestDto updatedRequestDto, @MappingTarget User userToUpdate);
```
be attentive with copy-pasting))

2023-11-30 10:43 UTC, liliia-ponomarenko commented on src/main/java/model/Role.java
> +
move the nested class after fields and methods

2023-11-30 10:43 UTC, liliia-ponomarenko commented on src/main/java/model/Role.java
> +    @Column(name = "name", nullable = false, unique = true)
```suggestion
    @Column(nullable = false, unique = true)
```

2023-11-30 10:43 UTC, liliia-ponomarenko commented on src/main/java/model/User.java
> +
```suggestion
```
also better exclude this field from methods toString, equals and hash-code

2023-11-30 10:43 UTC, liliia-ponomarenko commented on src/main/java/security/CustomUserDetailsService.java
> +    public UserDetails loadUserByUsername(String username) throws UsernameNotFoundException {
```suggestion
    public UserDetails loadUserByUsername(String username) {
```

2023-11-30 10:43 UTC, liliia-ponomarenko commented on src/main/java/service/impl/UserServiceImpl.java
> +            throw new RegistrationException("Registration failed");
Let’s provide a more informative message

2023-11-30 10:43 UTC, liliia-ponomarenko commented on src/main/java/service/impl/UserServiceImpl.java
> +@Component
```suggestion
@Service
@RequiredArgsConstructor
```
One annotation enough )

2023-12-01 12:30 UTC, liliia-ponomarenko approved these changes
Great 😌

2023-12-04 07:22 UTC, Elena-Bruyako requested changes
Good job! Let's improve your solution!

2023-12-04 07:22 UTC, Elena-Bruyako commented on pom.xml
> +        <version>4.22.0</version>
You don't need to declare version, spring-boot-starter-parent already includes it

2023-12-04 07:22 UTC, Elena-Bruyako commented on src/main/java/dto/user/UserRegistrationRequestDto.java
> +public record UserRegistrationRequestDto(
You should add FieldMatch annotation for checking that password and repeatPassword field in the UserRegistrationRequestDto are the same (see in requirements) 

Create FieldMatch annotation and use it
```
@FieldMatch(
        fields = {"password", "repeatPassword"},
        message = "Password and repeated password must be equal"
)
```

and create FieldMatcher

2023-12-04 07:22 UTC, Elena-Bruyako commented on src/main/java/model/Role.java
> +
```suggestion
```

2023-12-04 07:22 UTC, Elena-Bruyako commented on src/main/java/model/User.java
> +    @ManyToMany
`@ToString.Exclude`

2023-12-04 07:22 UTC, Elena-Bruyako commented on src/main/java/service/impl/UserServiceImpl.java
> +        if (userRepository.findByEmail(request.email()).isPresent()) {
It's better to create existsByEmail method in repo to avoid calling isPresent()

2023-12-05 10:15 UTC, liliia-ponomarenko approved these changes
Good job! But fix some mistakes before merging;)

2023-12-05 10:15 UTC, liliia-ponomarenko commented on src/main/java/security/validator/FieldMatch.java
> +}
add empty line

2023-12-05 10:15 UTC, liliia-ponomarenko commented on src/main/java/security/validator/FieldMatcherValidator.java
> +}
the same

2023-12-05 12:01 UTC, merged